// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#import <Foundation/Foundation.h>

typedef uint32_t OCTToxDNSRequestId;

/**
 * Object generated by OCTToxDNS.
 */
@interface OCTToxDNS3Object : NSObject

/**
 * String generated by OCTToxDNS for given name. Use this string to perform DNS request.
 *
 * This is what the string returned looks like:
 * 4haaaaipr1o3mz0bxweox541airydbovqlbju51mb4p0ebxq.rlqdj4kkisbep2ks3fj2nvtmk4daduqiueabmexqva1jc
 */
@property (copy, nonatomic) NSString *generatedString;

/**
 * Name for which string was generated.
 */
@property (copy, nonatomic) NSString *name;

/**
 * Request id that was generated by OCTToxDNS.
 */
@property (assign, nonatomic) OCTToxDNSRequestId requestId;

@end
